### ISSUE TITLE
Send to PostCSS plugins catalog

### ISSUE THREAD

**Issue by ai** [TomerAberbach/postcss-fontpie#1]
Amazing plugin! I will try to promote it in `@postcss` Twitter too.

Can you send it to https://www.postcss.parts/ ?

**Comment by TomerAberbach** [comment]
Thank you! Much appreciated

Yup, I can send it to postcss.parts sometime this week. Will keep this issue open until I do that

**Comment by TomerAberbach** [comment]
https://github.com/himynameisdave/postcss-plugins/pull/348
