### ISSUE TITLE
`postcss-values-parser` is very difficult to work with for end users

### ISSUE THREAD

**Issue by romainmenke** [TomerAberbach/postcss-fontpie#2]
https://github.com/TomerAberbach/postcss-fontpie/blob/db89036a191a777ed2497804c54c8ebf88d19741/package.json#L53

see : https://github.com/shellscape/postcss-values-parser/issues/143

Would you accept a pull request to change to a more reliable value parser?

**Comment by TomerAberbach** [comment]
Seems that issue is closed now. Is it erroneously closed? If so, then sure, I would accept a PR if we can largely retain the same behavior

**Comment by romainmenke** [comment]
Issue was closed because the author no longer intends to fix it in the current major.
They are migrating their package to css-tree, which would eliminate the underlying problem.
But all work on this migration has halted :/
