### ISSUE TITLE
Add option to suppress 'Missing font type mapping' warnings

### ISSUE THREAD

**Issue by kripod** [TomerAberbach/postcss-fontpie#6]
While trying to integrate this plugin in an Astro project, the parameter provided by `srcUrlToFilename` couldn’t be used, as sometimes, the `url` has a format similar to `.__VITE_ASSET__abcd1234__`.

In order to mitigate the issue, I came up with the idea of including the plugin twice and returning a static path via `srcUrlToFilename`. However, the following `postcss.config.cjs` produces unwanted 'Missing font type mapping' warnings as a result:

```js
const postcssFontpie = require("postcss-fontpie");

const atkinsonHyperlegibleFilename = require.resolve(
  "@fontsource/atkinson-hyperlegible/files/atkinson-hyperlegible-latin-400-normal.woff2",
);
const jetBrainsMonoFilename = require.resolve(
  "@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2",
);

module.exports = {
  plugins: [
    postcssFontpie({
      fontTypes: { "Atkinson Hyperlegible": "sans-serif" },
      srcUrlToFilename: () => atkinsonHyperlegibleFilename,
    }),
    postcssFontpie({
      fontTypes: { "JetBrains Mono": "mono" },
      srcUrlToFilename: () => jetBrainsMonoFilename,
    }),
  ],
};
```

I’d propose an option to suppress such warnings as a mitigation.

**Comment by TomerAberbach** [comment]
Gonna implement #7 instead
